project_name: fiddle

archives:
  - id: fiddle
    files:
      - LICENSE
    format: tar.gz
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"

brews:
  - name: fiddle
    commit_author:
      name: Kamil Samigullin
      email: kamil@samigullin.info
    description: The missing RSS manager.
    folder: Formula
    homepage: https://fiddle.octolab.org/
    repository:
      owner: octolab
      name: homebrew-tap
    install: |
      bin.install "fiddle"

      output = Utils.popen_read("#{bin}/fiddle completion bash")
      (bash_completion/"fiddle").write output

      output = Utils.popen_read("#{bin}/fiddle completion fish")
      (fish_completion/"fiddle.fish").write output

      output = Utils.popen_read("#{bin}/fiddle completion zsh")
      (zsh_completion/"_fiddle").write output

      prefix.install_metafiles
    test: |
      system "#{bin}/fiddle version"

builds:
  - id: fiddle
    binary: fiddle
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    main: .

checksum: { name_template: checksums.txt }

release:
  github:
    owner: tact-app
    name: fiddle
